ALTER TABLE activity_template_set
  ADD COLUMN IF NOT EXISTS periods JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS special_days JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS attributes JSONB;
