import type { CustomAttributeTarget } from './custom-attribute.types';

export const CUSTOM_ATTRIBUTE_TARGETS: CustomAttributeTarget[] = [
  {
    id: 'personnel-service-pools',
    label: 'Personaldienstpools',
    group: 'personal',
    description: 'Zusätzliche Attribute für Personaldienstpools',
  },
  {
    id: 'personnel-services',
    label: 'Personaldienste',
    group: 'personal',
    description: 'Attribute für einzelne Personaldienste',
  },
  {
    id: 'personnel-pools',
    label: 'Personalpools',
    group: 'personal',
    description: 'Attribute für Personalpools',
  },
  {
    id: 'personnel',
    label: 'Mitarbeitende',
    group: 'personal',
    description: 'Attribute für einzelne Mitarbeitende',
  },
  {
    id: 'vehicle-service-pools',
    label: 'Fahrzeugdienstpools',
    group: 'vehicle',
    description: 'Attribute für Fahrzeugdienstpools',
  },
  {
    id: 'vehicle-services',
    label: 'Fahrzeugdienste',
    group: 'vehicle',
    description: 'Attribute für einzelne Fahrzeugdienste',
  },
  {
    id: 'vehicle-pools',
    label: 'Fahrzeugpools',
    group: 'vehicle',
    description: 'Attribute für Fahrzeugpools',
  },
  {
    id: 'vehicles',
    label: 'Fahrzeuge',
    group: 'vehicle',
    description: 'Attribute für einzelne Fahrzeuge',
  },
  {
    id: 'vehicle-types',
    label: 'Fahrzeugtypen',
    group: 'vehicle',
    description: 'Attribute für Fahrzeugtypen',
  },
  {
    id: 'vehicle-compositions',
    label: 'Fahrzeugkompositionen',
    group: 'vehicle',
    description: 'Attribute für Fahrzeugkompositionen',
  },
  {
    id: 'topology-operational-points',
    label: 'Topologie – Betriebsstellen',
    group: 'general',
    description: 'Attribute für Operational Points im Planungsnetz.',
  },
  {
    id: 'topology-sections-of-line',
    label: 'Topologie – Streckenabschnitte',
    group: 'general',
    description: 'Attribute für Sections of Line.',
  },
  {
    id: 'topology-station-areas',
    label: 'Topologie – Bahnhofsbereiche',
    group: 'general',
    description: 'Attribute für Station Areas (Bahnhofsbereiche).',
  },
  {
    id: 'topology-tracks',
    label: 'Topologie – Bahnhofsgleise',
    group: 'general',
    description: 'Attribute für Tracks innerhalb von Bahnhöfen.',
  },
  {
    id: 'topology-platform-edges',
    label: 'Topologie – Bahnsteigkanten',
    group: 'general',
    description: 'Attribute für Platform Edges (Bahnsteigkanten).',
  },
  {
    id: 'topology-platforms',
    label: 'Topologie – Bahnsteige',
    group: 'general',
    description: 'Attribute für Platforms (Bahnsteige).',
  },
  {
    id: 'topology-sidings',
    label: 'Topologie – Abstellgleise',
    group: 'general',
    description: 'Attribute für Sidings (Abstellgleise).',
  },
  {
    id: 'topology-personnel-sites',
    label: 'Topologie – Personaleinsatzstellen',
    group: 'general',
    description: 'Attribute für Personnel Sites (Meldestellen, Pausenräume etc.).',
  },
  {
    id: 'topology-replacement-stops',
    label: 'Topologie – Ersatzhaltestellen',
    group: 'general',
    description: 'Attribute für Replacement Stops im SEV.',
  },
  {
    id: 'topology-replacement-routes',
    label: 'Topologie – Ersatzlinien',
    group: 'general',
    description: 'Attribute für Replacement Routes im SEV.',
  },
  {
    id: 'topology-replacement-edges',
    label: 'Topologie – Ersatzkanten',
    group: 'general',
    description: 'Attribute für Replacement Edges zwischen Ersatzhaltestellen.',
  },
  {
    id: 'topology-op-replacement-links',
    label: 'Topologie – OP↔SEV-Verknüpfungen',
    group: 'general',
    description: 'Attribute für Links zwischen Operational Points und Replacement Stops.',
  },
  {
    id: 'topology-transfer-edges',
    label: 'Topologie – Transferkanten',
    group: 'general',
    description: 'Attribute für Transfer Edges (Fußwege, Shuttles, interne Wege).',
  },
];
