export const ALLOWED_ACTIONS = new Set([
  'none',
  'batch',
  'create_personnel_service_pool',
  'create_vehicle_service_pool',
  'create_personnel_service',
  'create_vehicle_service',
  'create_personnel_pool',
  'create_vehicle_pool',
  'create_home_depot',
  'create_personnel',
  'create_vehicle',
  'create_vehicle_type',
  'create_vehicle_composition',
  'create_timetable_year',
  'create_simulation',
  'create_operational_point',
  'create_section_of_line',
  'create_personnel_site',
  'create_replacement_stop',
  'create_replacement_route',
  'create_replacement_edge',
  'create_op_replacement_stop_link',
  'create_transfer_edge',
  'create_activity_template',
  'create_activity_definition',
  'create_layer_group',
  'create_custom_attribute',
  'update_personnel_service_pool',
  'update_vehicle_service_pool',
  'update_personnel_pool',
  'update_vehicle_pool',
  'update_home_depot',
  'update_personnel_service',
  'update_vehicle_service',
  'update_personnel',
  'update_vehicle',
  'update_vehicle_type',
  'update_vehicle_composition',
  'update_simulation',
  'update_operational_point',
  'update_section_of_line',
  'update_personnel_site',
  'update_replacement_stop',
  'update_replacement_route',
  'update_replacement_edge',
  'update_op_replacement_stop_link',
  'update_transfer_edge',
  'update_activity_template',
  'update_activity_definition',
  'update_layer_group',
  'update_translations',
  'update_custom_attribute',
  'delete_personnel_service_pool',
  'delete_vehicle_service_pool',
  'delete_personnel_pool',
  'delete_vehicle_pool',
  'delete_home_depot',
  'delete_personnel_service',
  'delete_vehicle_service',
  'delete_personnel',
  'delete_vehicle',
  'delete_vehicle_type',
  'delete_vehicle_composition',
  'delete_timetable_year',
  'delete_simulation',
  'delete_operational_point',
  'delete_section_of_line',
  'delete_personnel_site',
  'delete_replacement_stop',
  'delete_replacement_route',
  'delete_replacement_edge',
  'delete_op_replacement_stop_link',
  'delete_transfer_edge',
  'delete_activity_template',
  'delete_activity_definition',
  'delete_layer_group',
  'delete_translation_locale',
  'delete_custom_attribute',
]);

export const ROOT_FIELDS_BY_ACTION: Record<string, string[]> = {
  none: ['action', 'reason'],
  batch: ['action', 'actions', 'reason'],
  create_personnel_service_pool: ['action', 'pool', 'services', 'reason'],
  create_vehicle_service_pool: ['action', 'pool', 'services', 'reason'],
  create_personnel_service: ['action', 'pool', 'services', 'items', 'reason'],
  create_vehicle_service: ['action', 'pool', 'services', 'items', 'reason'],
  create_personnel_pool: ['action', 'pool', 'reason'],
  create_vehicle_pool: ['action', 'pool', 'reason'],
  create_home_depot: ['action', 'homeDepot', 'homeDepots', 'items', 'reason'],
  create_personnel: ['action', 'personnel', 'pool', 'items', 'reason'],
  create_vehicle: ['action', 'vehicles', 'pool', 'items', 'reason'],
  create_vehicle_type: [
    'action',
    'vehicleType',
    'vehicleTypes',
    'items',
    'reason',
  ],
  create_vehicle_composition: [
    'action',
    'vehicleComposition',
    'vehicleCompositions',
    'items',
    'reason',
  ],
  create_timetable_year: [
    'action',
    'timetableYear',
    'timetableYears',
    'items',
    'reason',
  ],
  create_simulation: ['action', 'simulation', 'simulations', 'items', 'reason'],
  create_operational_point: [
    'action',
    'operationalPoint',
    'operationalPoints',
    'items',
    'reason',
  ],
  create_section_of_line: [
    'action',
    'sectionOfLine',
    'sectionsOfLine',
    'items',
    'reason',
  ],
  create_personnel_site: [
    'action',
    'personnelSite',
    'personnelSites',
    'items',
    'reason',
  ],
  create_replacement_stop: [
    'action',
    'replacementStop',
    'replacementStops',
    'items',
    'reason',
  ],
  create_replacement_route: [
    'action',
    'replacementRoute',
    'replacementRoutes',
    'items',
    'reason',
  ],
  create_replacement_edge: [
    'action',
    'replacementEdge',
    'replacementEdges',
    'items',
    'reason',
  ],
  create_op_replacement_stop_link: [
    'action',
    'opReplacementStopLink',
    'opReplacementStopLinks',
    'items',
    'reason',
  ],
  create_transfer_edge: [
    'action',
    'transferEdge',
    'transferEdges',
    'items',
    'reason',
  ],
  update_personnel_service_pool: ['action', 'target', 'patch', 'reason'],
  update_vehicle_service_pool: ['action', 'target', 'patch', 'reason'],
  update_personnel_pool: ['action', 'target', 'patch', 'reason'],
  update_vehicle_pool: ['action', 'target', 'patch', 'reason'],
  update_home_depot: ['action', 'target', 'patch', 'reason'],
  update_personnel_service: ['action', 'target', 'patch', 'reason'],
  update_vehicle_service: ['action', 'target', 'patch', 'reason'],
  update_personnel: ['action', 'target', 'patch', 'reason'],
  update_vehicle: ['action', 'target', 'patch', 'reason'],
  update_vehicle_type: ['action', 'target', 'patch', 'reason'],
  update_vehicle_composition: ['action', 'target', 'patch', 'reason'],
  update_simulation: ['action', 'target', 'patch', 'reason'],
  update_operational_point: ['action', 'target', 'patch', 'reason'],
  update_section_of_line: ['action', 'target', 'patch', 'reason'],
  update_personnel_site: ['action', 'target', 'patch', 'reason'],
  update_replacement_stop: ['action', 'target', 'patch', 'reason'],
  update_replacement_route: ['action', 'target', 'patch', 'reason'],
  update_replacement_edge: ['action', 'target', 'patch', 'reason'],
  update_op_replacement_stop_link: ['action', 'target', 'patch', 'reason'],
  update_transfer_edge: ['action', 'target', 'patch', 'reason'],
  delete_personnel_service_pool: ['action', 'target', 'reason'],
  delete_vehicle_service_pool: ['action', 'target', 'reason'],
  delete_personnel_pool: ['action', 'target', 'reason'],
  delete_vehicle_pool: ['action', 'target', 'reason'],
  delete_home_depot: ['action', 'target', 'reason'],
  delete_personnel_service: ['action', 'target', 'reason'],
  delete_vehicle_service: ['action', 'target', 'reason'],
  delete_personnel: ['action', 'target', 'reason'],
  delete_vehicle: ['action', 'target', 'reason'],
  delete_vehicle_type: ['action', 'target', 'reason'],
  delete_vehicle_composition: ['action', 'target', 'reason'],
  delete_timetable_year: ['action', 'target', 'reason'],
  delete_simulation: ['action', 'target', 'reason'],
  delete_operational_point: ['action', 'target', 'reason'],
  delete_section_of_line: ['action', 'target', 'reason'],
  delete_personnel_site: ['action', 'target', 'reason'],
  delete_replacement_stop: ['action', 'target', 'reason'],
  delete_replacement_route: ['action', 'target', 'reason'],
  delete_replacement_edge: ['action', 'target', 'reason'],
  delete_op_replacement_stop_link: ['action', 'target', 'reason'],
  delete_transfer_edge: ['action', 'target', 'reason'],
  create_activity_template: [
    'action',
    'activityTemplate',
    'activityTemplates',
    'items',
    'reason',
  ],
  create_activity_definition: [
    'action',
    'activityDefinition',
    'activityDefinitions',
    'items',
    'reason',
  ],
  create_layer_group: [
    'action',
    'layerGroup',
    'layerGroups',
    'items',
    'reason',
  ],
  update_activity_template: ['action', 'target', 'patch', 'reason'],
  update_activity_definition: ['action', 'target', 'patch', 'reason'],
  update_layer_group: ['action', 'target', 'patch', 'reason'],
  delete_activity_template: ['action', 'target', 'reason'],
  delete_activity_definition: ['action', 'target', 'reason'],
  delete_layer_group: ['action', 'target', 'reason'],
  update_translations: [
    'action',
    'translations',
    'translation',
    'items',
    'locale',
    'reason',
  ],
  delete_translation_locale: ['action', 'locale', 'target', 'reason'],
  create_custom_attribute: [
    'action',
    'customAttribute',
    'customAttributes',
    'items',
    'reason',
  ],
  update_custom_attribute: ['action', 'target', 'patch', 'reason'],
  delete_custom_attribute: ['action', 'target', 'reason'],
};

export const DEFAULT_ROOT_FIELDS = [
  'action',
  'schemaVersion',
  'reason',
  'pool',
  'poolName',
  'servicePool',
  'personnelServicePool',
  'vehicleServicePool',
  'personnelPool',
  'vehiclePool',
  'homeDepot',
  'homeDepots',
  'vehicleType',
  'vehicleTypes',
  'vehicleComposition',
  'vehicleCompositions',
  'timetableYear',
  'timetableYears',
  'simulation',
  'simulations',
  'operationalPoint',
  'operationalPoints',
  'sectionOfLine',
  'sectionsOfLine',
  'personnelSite',
  'personnelSites',
  'replacementStop',
  'replacementStops',
  'replacementRoute',
  'replacementRoutes',
  'replacementEdge',
  'replacementEdges',
  'opReplacementStopLink',
  'opReplacementStopLinks',
  'transferEdge',
  'transferEdges',
  'activityTemplate',
  'activityTemplates',
  'activityDefinition',
  'activityDefinitions',
  'layerGroup',
  'layerGroups',
  'translations',
  'translation',
  'locale',
  'customAttribute',
  'customAttributes',
  'service',
  'services',
  'personnelService',
  'vehicleService',
  'personnel',
  'person',
  'people',
  'vehicles',
  'vehicle',
  'target',
  'patch',
  'items',
  'actions',
];

export const POOL_KEYS = [
  'id',
  'poolId',
  'name',
  'poolName',
  'description',
  'homeDepotId',
  'homeDepot',
  'homeDepotName',
  'locationCode',
  'shiftCoordinator',
  'contactEmail',
  'dispatcher',
  'depotManager',
  'serviceIds',
  'services',
];

export const SERVICE_KEYS = [
  'id',
  'name',
  'serviceName',
  'description',
  'poolId',
  'poolName',
  'pool',
  'startTime',
  'endTime',
  'isNightService',
  'requiredQualifications',
  'maxDailyInstances',
  'maxResourcesPerInstance',
  'isOvernight',
  'primaryRoute',
];

export const PERSONNEL_KEYS = [
  'id',
  'personnelId',
  'firstName',
  'lastName',
  'name',
  'fullName',
  'label',
  'preferredName',
  'qualifications',
  'serviceIds',
  'services',
  'serviceNames',
  'poolId',
  'poolName',
  'pool',
  'homeStation',
  'availabilityStatus',
  'qualificationExpires',
  'isReserve',
];

export const VEHICLE_KEYS = [
  'id',
  'vehicleId',
  'vehicleNumber',
  'number',
  'name',
  'label',
  'typeId',
  'type',
  'typeLabel',
  'vehicleType',
  'poolId',
  'poolName',
  'pool',
  'serviceIds',
  'services',
  'serviceNames',
  'description',
  'depot',
];

export const TARGET_KEYS = [
  'id',
  'name',
  'label',
  'poolId',
  'poolName',
  'serviceName',
  'serviceId',
  'personnelId',
  'vehicleId',
  'vehicleNumber',
  'typeId',
  'typeLabel',
  'vehicleType',
  'timetableYearLabel',
  'simulationId',
  'variantId',
  'opId',
  'uniqueOpId',
  'solId',
  'siteId',
  'replacementStopId',
  'replacementRouteId',
  'replacementEdgeId',
  'linkId',
  'transferId',
  'compositionId',
  'entityId',
  'entity_id',
  'key',
  'locale',
];

export const PATCH_KEYS = [
  'name',
  'label',
  'description',
  'poolId',
  'poolName',
  'homeDepotId',
  'homeDepot',
  'homeDepotName',
  'locationCode',
  'shiftCoordinator',
  'contactEmail',
  'dispatcher',
  'depotManager',
  'services',
  'serviceIds',
  'serviceNames',
  'firstName',
  'lastName',
  'preferredName',
  'qualifications',
  'homeStation',
  'availabilityStatus',
  'qualificationExpires',
  'isReserve',
  'vehicleNumber',
  'typeId',
  'typeLabel',
  'vehicleType',
  'category',
  'capacity',
  'maxSpeed',
  'maintenanceIntervalDays',
  'energyType',
  'manufacturer',
  'trainTypeCode',
  'lengthMeters',
  'weightTons',
  'brakeType',
  'brakePercentage',
  'tiltingCapability',
  'powerSupplySystems',
  'trainProtectionSystems',
  'etcsLevel',
  'gaugeProfile',
  'maxAxleLoad',
  'noiseCategory',
  'remarks',
  'entries',
  'entriesSerialized',
  'turnaroundBuffer',
  'remark',
  'timetableYearLabel',
  'opId',
  'uniqueOpId',
  'countryCode',
  'opType',
  'position',
  'lat',
  'lng',
  'startUniqueOpId',
  'endUniqueOpId',
  'lengthKm',
  'nature',
  'siteType',
  'openingHoursJson',
  'nearestUniqueOpId',
  'stationCategory',
  'attributes',
  'replacementRouteId',
  'replacementStopId',
  'seq',
  'relationType',
  'walkingTimeSec',
  'distanceM',
  'from',
  'to',
  'mode',
  'avgDurationSec',
  'bidirectional',
  'appliesTo',
  'applies_to',
  'relevantFor',
  'relevant_for',
  'timeMode',
  'time_mode',
  'fields',
  'defaultDurationMinutes',
  'default_duration_minutes',
  'activityType',
  'activity_type',
  'templateId',
  'template_id',
  'order',
  'sort_order',
  'meta',
  'entityId',
  'entity_id',
  'key',
  'type',
  'temporal',
  'required',
  'presets',
];

export const HOME_DEPOT_KEYS = [
  'id',
  'homeDepotId',
  'name',
  'label',
  'description',
  'siteIds',
  'breakSiteIds',
  'shortBreakSiteIds',
  'overnightSiteIds',
];

export const VEHICLE_TYPE_KEYS = [
  'id',
  'typeId',
  'label',
  'name',
  'category',
  'capacity',
  'maxSpeed',
  'maintenanceIntervalDays',
  'energyType',
  'manufacturer',
  'trainTypeCode',
  'lengthMeters',
  'weightTons',
  'brakeType',
  'brakePercentage',
  'tiltingCapability',
  'powerSupplySystems',
  'trainProtectionSystems',
  'etcsLevel',
  'gaugeProfile',
  'maxAxleLoad',
  'noiseCategory',
  'remarks',
];

export const VEHICLE_COMPOSITION_KEYS = [
  'id',
  'compositionId',
  'name',
  'label',
  'entries',
  'entriesSerialized',
  'turnaroundBuffer',
  'remark',
];

export const TIMETABLE_YEAR_KEYS = [
  'id',
  'label',
  'name',
  'timetableYearLabel',
  'startDate',
  'endDate',
];

export const SIMULATION_KEYS = [
  'id',
  'label',
  'name',
  'timetableYear',
  'timetableYearLabel',
  'description',
];

export const OPERATIONAL_POINT_KEYS = [
  'id',
  'opId',
  'uniqueOpId',
  'name',
  'label',
  'countryCode',
  'opType',
  'position',
  'lat',
  'lng',
];

export const SECTION_OF_LINE_KEYS = [
  'id',
  'solId',
  'startUniqueOpId',
  'endUniqueOpId',
  'lengthKm',
  'nature',
];

export const PERSONNEL_SITE_KEYS = [
  'id',
  'siteId',
  'siteType',
  'name',
  'label',
  'uniqueOpId',
  'position',
  'lat',
  'lng',
  'openingHoursJson',
];

export const REPLACEMENT_STOP_KEYS = [
  'id',
  'replacementStopId',
  'name',
  'label',
  'nearestUniqueOpId',
  'stationCategory',
  'position',
  'lat',
  'lng',
  'attributes',
];

export const REPLACEMENT_ROUTE_KEYS = [
  'id',
  'replacementRouteId',
  'name',
  'label',
  'description',
];

export const REPLACEMENT_EDGE_KEYS = [
  'id',
  'replacementEdgeId',
  'replacementRouteId',
  'replacementStopId',
  'seq',
  'attributes',
];

export const OP_REPLACEMENT_STOP_LINK_KEYS = [
  'id',
  'linkId',
  'uniqueOpId',
  'replacementStopId',
  'relationType',
  'walkingTimeSec',
  'distanceM',
  'attributes',
];

export const TRANSFER_EDGE_KEYS = [
  'id',
  'transferId',
  'from',
  'to',
  'mode',
  'avgDurationSec',
  'distanceM',
  'bidirectional',
  'attributes',
];

export const ACTIVITY_TEMPLATE_KEYS = [
  'id',
  'templateId',
  'label',
  'name',
  'description',
  'activityType',
  'activity_type',
  'defaultDurationMinutes',
  'default_duration_minutes',
  'attributes',
];

export const ACTIVITY_DEFINITION_KEYS = [
  'id',
  'definitionId',
  'label',
  'name',
  'description',
  'activityType',
  'activity_type',
  'templateId',
  'template_id',
  'defaultDurationMinutes',
  'default_duration_minutes',
  'relevantFor',
  'relevant_for',
  'attributes',
  'presets',
];

export const LAYER_GROUP_KEYS = [
  'id',
  'label',
  'name',
  'order',
  'sort_order',
  'description',
];

export const TRANSLATION_KEYS = [
  'locale',
  'key',
  'label',
  'abbreviation',
  'delete',
  'remove',
];

export const CUSTOM_ATTRIBUTE_KEYS = [
  'id',
  'key',
  'label',
  'name',
  'type',
  'description',
  'entityId',
  'entity_id',
  'createdAt',
  'updatedAt',
  'temporal',
  'required',
];
