import type { AssistantContextResource } from './assistant-context.types';

export const RESOURCE_LABELS: Record<AssistantContextResource, string> = {
  personnelServicePools: 'Personaldienstpools',
  personnelServices: 'Personaldienste',
  personnelPools: 'Personalpools',
  homeDepots: 'Heimdepots',
  personnel: 'Personal',
  vehicleServicePools: 'Fahrzeugdienstpools',
  vehicleServices: 'Fahrzeugdienste',
  vehiclePools: 'Fahrzeugpools',
  vehicles: 'Fahrzeuge',
  vehicleTypes: 'Fahrzeugtypen',
  vehicleCompositions: 'Fahrzeugkompositionen',
  timetableYears: 'Fahrplanjahre',
  simulations: 'Simulationen',
  operationalPoints: 'Operational Points',
  sectionsOfLine: 'Sections of Line',
  personnelSites: 'Personnel Sites',
  replacementStops: 'Replacement Stops',
  replacementRoutes: 'Replacement Routes',
  replacementEdges: 'Replacement Edges',
  opReplacementStopLinks: 'OP <-> Replacement Links',
  transferEdges: 'Transfer Edges',
};

export const RESOURCE_FIELDS: Record<AssistantContextResource, string[]> = {
  personnelServicePools: [
    'name',
    'description',
    'homeDepotId',
    'serviceCount',
    'shiftCoordinator',
    'contactEmail',
  ],
  personnelServices: [
    'name',
    'startTime',
    'endTime',
    'isNightService',
    'maxDailyInstances',
    'maxResourcesPerInstance',
  ],
  personnelPools: [
    'name',
    'description',
    'homeDepotId',
    'locationCode',
    'personnelCount',
  ],
  homeDepots: [
    'name',
    'description',
    'siteCount',
    'breakSiteCount',
    'shortBreakSiteCount',
    'overnightSiteCount',
  ],
  personnel: ['fullName', 'qualifications', 'serviceCount', 'poolId'],
  vehicleServicePools: ['name', 'description', 'dispatcher', 'serviceCount'],
  vehicleServices: [
    'name',
    'startTime',
    'endTime',
    'isOvernight',
    'primaryRoute',
  ],
  vehiclePools: ['name', 'description', 'depotManager', 'vehicleCount'],
  vehicles: [
    'vehicleNumber',
    'typeId',
    'depot',
    'serviceCount',
    'description',
    'poolId',
  ],
  vehicleTypes: [
    'label',
    'category',
    'capacity',
    'maxSpeed',
    'energyType',
    'manufacturer',
    'lengthMeters',
  ],
  vehicleCompositions: [
    'name',
    'entrySummary',
    'entryCount',
    'turnaroundBuffer',
  ],
  timetableYears: ['label', 'simulationCount', 'variantCount'],
  simulations: ['label', 'timetableYearLabel', 'description'],
  operationalPoints: ['uniqueOpId', 'name', 'countryCode', 'opType'],
  sectionsOfLine: [
    'solId',
    'startUniqueOpId',
    'endUniqueOpId',
    'lengthKm',
    'nature',
  ],
  personnelSites: ['siteId', 'name', 'siteType', 'uniqueOpId'],
  replacementStops: [
    'replacementStopId',
    'name',
    'stopCode',
    'nearestUniqueOpId',
  ],
  replacementRoutes: ['replacementRouteId', 'name', 'operator'],
  replacementEdges: [
    'replacementEdgeId',
    'replacementRouteId',
    'fromStopId',
    'toStopId',
    'seq',
    'avgDurationSec',
  ],
  opReplacementStopLinks: [
    'linkId',
    'uniqueOpId',
    'replacementStopId',
    'relationType',
  ],
  transferEdges: [
    'transferId',
    'from',
    'to',
    'mode',
    'avgDurationSec',
    'bidirectional',
  ],
};
